---
version: "3.7"

services:
  caddy:
    image: caddy:local
    container_name: caddy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/data
      - ./config:/config
      - ~/s.hotbun.co:/var/www/s.hotbun.co
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
    restart: unless-stopped
