---
version: "3.7"

services:
  caddy:
    image: caddy:local
    container_name: caddy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/data
      - ./config:/config
      - ~/s.pavlenko.sh:/var/www/s.pavlenko.sh
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
    restart: unless-stopped
