---
version: "3.7"

services:
  transmission:
    image: lscr.io/linuxserver/transmission:4.0.5
    container_name: transmission
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - USER=${username}
      - PASS=${password}
    volumes:
      - ./transmission-config:/config
      - /media/transmission/watch:/watch
      - /media/emby/tv:/downloads/tv
      - /media/emby/movies:/downloads/movies
      - /media/emby/tvanimation:/downloads/tvanimation
      - /media/emby/animation:/downloads/animation
    restart: unless-stopped
  
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
      - 9091:9091
      - 55352:55352/tcp
      - 55352:55352/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

